### ISSUE TITLE
Data storage finder

### ISSUE THREAD

**Issue by jpvmiltenburg** [Deltares-research/data-management-suite#94]
## 🚀 Feature Request

As a researcher I would like to have an interactive tool to help me find a suitable data storage solution for my project.

The UU storage finder is a great inspiration: https://tools.uu.nl/storagefinder/

The exact content of the tool will follow

**Comment by RobertBroersma** [comment]
I've created a draft PR for this to show how it could work. I included only one page of detailed content for P:/. The content is not final yet, right? @jpvmiltenburg
